# Generated by Django 4.2.11 on 2026-04-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['label'], name='images_imag_label_92f522_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['timestamp'], name='images_imag_timesta_be8973_idx'),
        ),
    ]
